config/routes.rb
Shpora::Application.routes.draw do
  get "welcome/index"
  get "omniauth_callbacks/vkontakte"
 devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks"},
                     path_names:  { sign_up: 'register', sign_in: 'login', sign_out: 'logout' }
root 'welcome#index'
resources :users, only: [:index, :show] do
  resources :messages
  get 'messages/sended'
  get 'messages/recived'
end

resources :posts do
  resources :comments
end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
  belongs_to :recepient, class_name: 'User', foreign_key: 'recepient_id'



  def read
    self.read_at = true
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  default_scope { order("created_at DESC") }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  has_many :recepient_messages, class_name: 'Message', foreign_key: 'recepient_id'
  has_many :sended_messages, class_name: 'Message', foreign_key: 'sender_id'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  def self.find_for_vkontakte_oauth access_token
    if user = User.where(:url => access_token.info.urls.Vkontakte).first
      user
    else
      User.create!(:provider => access_token.provider, :url => access_token.info.urls.Vkontakte, :username => access_token.info.name, :nickname => access_token.extra.raw_info.domain, :email => access_token.extra.raw_info.domain+'<hh user=vk>.com', :password => Devise.friendly_token[0,20])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def show
    @comment = current_user.comments.find(comment_params)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment == current_user
    @comment.destroy
    redirect_to post_path(@post)

  end

  private

  def comment_params
    params.require(:comment).permit(:name, :body, :post_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def sended
    @users = User.all
    @messages = current_user.sended_messages.all
  end

  def recived
    @users = User.all
    @messages = current_user.recepiend_messages.all
  end

  def new
    @user = User.find(params[:user_id])
    @message = @user.recepient_messages.new

  end

  def create
    @message = current_user.sended_messages.create(message_params)
    redirect_to users_path
  end

  def show
    @message = Message.find(params[:id])
    @user = current_user
  end

  def destroy
    @message = Message.find(params[:id])
    if User.find(@message.sender_id) == current_user
      @message.delete_from_sended
      redirect_to messages_sended_path
    else
      @message.delete_from_recived
      redirect_to messages_recived_path
    end
  end

  private

    def message_params
     params.require(:message).permit(:tema, :content, :recepient_id, :read_at)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def index
    @posts = Post.paginate(page: params[:page], per_page: 6)
  end

  def new
    @post = Post.new

  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = current_user.posts.create(post_params)
    @post.save
    redirect_to posts_path
  end

  def update
    @post = Post.find(params[:id])
    @post.update_attributes(post_params)
    redirect_to posts_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, notice: "DELETE"
  end

  private

    def post_params
       params.require(:post).permit(:name, :text)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def new
    @user = User.new
  end

  def create
    @user = User.new(sign_up_params)
    if @user.save
      sign_up(:user, @user)
      redirect_to after_sign_up_path_for(posts_path)
    else
      render :new
    end
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :username) }
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController <  Devise::OmniauthCallbacksController
  def vkontakte
    <hh user=user> = User.find_for_vkontakte_oauth request.env["omniauth.auth"]
    if <hh user=user>.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Vkontakte"
      sign_in_and_redirect <hh user=user>, :event => :authentication
    else
      flash[:notice] = "authentication error"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(created_at: :desc)

  end

  def show
    @user = User.find(params[:id])
  end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/comments/show.html.haml
- @carrent_user.comments.each do |comment|

    %p Commenter:
      = comment.name
      = comment.body
      = f.hidden_field :post_id

app/views/layouts/_navbar.html.haml
%ul.nav.navbar-nav
  - if user_signed_in?
    %li{class: "active"}
      = link_to 'LOGOUT', destroy_user_session_path, method: :delete, confirm: "Are you sure"
  - else
    %li.active
      = link_to 'LOGIN', new_user_session_path
    %li
      = link_to 'REGISTRATION', new_user_registration_path
    %li
      = link_to "Sign in with Vkontakte", user_omniauth_authorize_path(:vkontakte)

app/views/layouts/_navbar1.html.haml
=javascript_include_tag "http://code.jquery.com/jquery-1.9.1.js", "http://code.jquery.com/ui/1.10.3/jquery-ui.js"
=stylesheet_link_tag "http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css"
:javascript
  $(function() {
    $("#dialog").dialog(
    {
      autoOpen: false
    });
    $("#dialog_link").on("click", function(e) {
      e.preventDefault();
      $("#dialog").dialog("open");
    });
  });

-if user_signed_in?
  .btn
    = link_to '  LOGOUT  ', destroy_user_session_path, method: :delete, class: "btn btn-primary", confirm: "Are you sure"
- else
  %div.page-header
    = link_to 'LOGIN', '#', class: "btn btn-success", id: "dialog_link"
    = link_to 'REGISTRATION', new_user_registration_path, class: "btn btn-primary"
%div{title: "Welcome...", id: "dialog", style: "display:none"}
  = form_tag user_session_path do
    = text_field_tag 'user[email]'
    = password_field_tag 'user[password]'
    %button Sign in

app/views/layouts/_profile.html.haml
- if user_signed_in?
  %li
    = link_to "EDIT PROFILE ", edit_user_registration_path
  %li
    = link_to "USERS", users_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Shpora
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-default.navbar-static-top
      .container
        .navbar-collapse.collapse
          %ul.navbar-nav.navbar-right
            = render 'layouts/navbar'
          %ul.nav.navbar-nav
            %li.active
              = link_to " HOME ", welcome_index_path
            -if user_signed_in?
              %li
                = link_to " All ", posts_path
              %li
                = link_to "ADD NEW ", new_post_path
            = render 'layouts/profile'


  .content
    = yield
  #footer
    .container
      %p.text-muted.credit
        First Petro's site &copy

app/views/messages/new.html.haml
.container
  .form-group
    .col-md-4.col-md-offset-4
      %h1.align New message
      = form_for [@user, @message] do |m|
        = m.hidden_field :recepient_id
        = m.hidden_field :read_at, value: :folse
        %br
        = m.text_field :tema, class: "form-control", placeholder: "Write Theme"
        %br
        = m.text_area :content, class: "form-control", placeholder: 'Your message text'
        %br
        .align
          = m.submit "Send", class: "btn btn-block btn-default"

app/views/messages/sended.html.haml
-@messages.each do |m|
    = m.tema
    = m.content

app/views/messages/show.html.haml
.container
      It is your inbox messages.
    %table{class: 'table'}
      %tr
        %th From
        %th Theme
        %th Content
      -@messages.each do |m|
        %tr
          %td
            #{User.find(m.sender_id).username}
          %td
            = m.tema
          %td
            = m.content

app/views/posts/create.html.haml
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/edit.html.haml
.container
  .align
    .form
      .form-group
        .row
          .col-md-6.col-md-offset-3
            %h1 Edit post
            = form_for @post do |c|
              %p
                = c.label :name, "Subject_name"
                = c.text_field :name, class: 'form-control'
              %p
                = c.label :text, 'Materials'
                = c.text_area :text, class: 'form-control editor'
              %p
                = c.submit "Update post", class: "btn btn-danger"

app/views/posts/index.html.haml
.container
  .row
    .shares.col-md-8.col-xs-8.align
      %h1.myfonts Subjects:
      .my
        -  @posts.each do |p|
          .row
            .container
              .form-group
                = link_to p.name, p, class: 'btn btn-default btn-lg btn-block'
                .row
                  .btn
                    = link_to "Edit", edit_post_path(p), class: 'btn btn-primary '
                    = link_to "Delete", p, confirm: 'Are you sure?', method: :delete, class: 'btn btn-danger'


    %h1.myfonts Tags:
    .shares.col-md-4.col-xs-4.align
      .my
        safasff


.container
  .align
    = will_paginate @posts

app/views/posts/new.html.haml
- if user_signed_in?
  .container
    .align
      .form
        .form-group
          .row
            .col-md-6.col-md-offset-3
              %h1 Add New Shpory
              = form_for @post do |c|
                %p
                  = c.label :Name, 'Subject name'
                  = c.text_field :name, class: 'form-control'
                %p
                  = c.label :text, 'Materials'
                  = c.text_area :text, class: 'editor form-control', rows: 10, cols: 68
                %p
                  = c.submit "Add a new shpory", class: 'btn btn-lg btn-primary btn-block'
- else
  .container
    .align
      %h1 If you want add new post, you need to #{link_to 'LOGIN', new_user_session_path, class: "btn btn-success"}

app/views/posts/show.html.haml
.align
  %h1.myfonts
    = @post.name
.container
  %p
    = raw(@post.text)
.container
  .form
    .form-group
      .row
        .align
          %h2.myfonts Comments
          - @post.comments.each do |comment|
            %br
              = raw(comment.body)
              %p
                Said Mr.
                = comment.user.username
                - if user_signed_in?
                  = link_to "Delete", [comment.post, comment], confirm: 'Are you sure?', method: :delete

.container
  .align
    .form
      .form-group
        .row
          .col-md-6.col-md-offset-3
            %h2.myfonts Add a Comment:
            = form_for([@post, @post.comments.build]) do |f|

              %p
                = f.hidden_field :post_id
                = f.label :body, "Comment content"
                = f.text_area :body, class: "form-control editor", rows: 10
              %p
                = f.submit "Create comment", class: "btn btn-primary"

app/views/users/index.html.haml
.container
  .align
    %h1 Profiles
  %table{class: 'table'}
    %tr
      - if user_signed_in?
        %th Username
        %th Email
        %th Message
        %th Last visit
        %th Recived
        %th Sended
        - @users.each do |user|
          %tr
            %td
              = user.username
            %td
              = link_to user.email, user
            %td
              = link_to "Send new ", new_user_message_path(user), class: "btn btn-default"
            %td
              = user.last_sign_in_at.to_s(:short)
            %td
              = link_to "Sended", user_messages_sended_path(user)
      - else
        %th Username
        %th Email
        %th Last visit
        - @users.each do |user|
          %tr
            %td
              = user.username
            %td
              = link_to user.email, user
            %td
              = user.last_sign_in_at.to_s(:short)

app/views/welcome/index.html.haml
.container
  .row
    .shares.col-md-4.col-xs-12
      %h2.align Sign in
      .form-group
        .row
          = form_tag session_path(:user) do
            .form-group
              = text_field_tag 'user[email]', nil, placeholder:"Email", class: "form-control "
            .form-group
              = password_field_tag 'user[password]', nil, placeholder:" Password ", class: "form-control"
            .form-group.align
              = check_box_tag 'user[remember_me]'
              = label_tag 'user[remember_me]', 'Remember me'
            %button.btn.btn-success.btn-block Sign in
            .form-group
              = link_to "Forgot your password?", new_password_path(:user)
    .shares.col-md-4.col-xs-12
      .content
        .align
          %h3
            This site will help you in everything, you'll get the highest mark in your class!!! Trust ME!!!
            Also you can view our content without registration!
          %h3
            =link_to "All content", posts_path, class: "btn btn-primary "
    .shares.col-md-4.col-xs-12
      %h2.align Sign up
      .form-group
        .row
          = form_tag registration_path(:user) do
            .form-group
              = text_field_tag 'user[username]', nil, placeholder: " Username ", class: "form-control"
            .form-group
              = text_field_tag 'user[email]', nil, placeholder: "Email", class: "form-control"
            .form-group
              = password_field_tag 'user[password]', nil, placeholder: "Password", class: "form-control"
            .form-group
              = password_field_tag 'user[password_confirmation]', nil, placeholder: "Confirmation password", class: "form-control"
            %button.btn.btn-success.btn-block  Sign up
  .row
    =image_tag('shpora/page.jpeg')